language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5bdb0588bfd0491fe9b0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false